spring.application.name=email-reply-assistant

server.port=8115

#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=This is email-reply-assistant application
info.app.version=3.5.13
info.app.description=This is smart-email-assistant build by me.

#Log file
logging.file.name=logs/email-reply.log
logging.level.com.niranjana=DEBUG
logging.logback.rollingpolicy.total-size-cap=100MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB

logging.level.root=INFO
logging.level.com.niranjana.ai.email=DEBUG

#GEMINI API
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.model=gemini-3-flash-preview
gemini.api.key=${GEMINI_API_KEY}

